<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>George R. R. Martin</title>
    <!-- Font Awesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- CSS File Link --> 
    <link rel="stylesheet" href="css/style3.css">
    <link rel="stylesheet" href="css/style.css">

</head>
<body>
<div class="george-heading">
   <h3>Author George</h3>
   <p> <a href="about.php">About Us</a> / Author George</p>
</div>

<div class="division0">
    <h1 class="walker-heading"> GEORGE R. R. MARTIN</h1>
    <i class="walker-sub-heading"> American Novelist </i>
    
    <div class="division1">
      <img src= "images/au2.jpg"><br><br>
      <p class="main">George Raymond Richard Martin (born George Raymond Martin; September 20, 1948), also known as GRRM</p>
    </div>
    
    <div class="division2">
      <b>
    <i class="alice-life">Here's a time line of GEORGE's life:</i>
    </b><br><br>
      <ul>
        <li> <b>Born</b> - George Raymond Martin; September 20, 1948</li>
      <br>  <li> <b>Why did George RR Martin stop writing Game of Thrones?</b> - "Writing a season six script would cost me a month's work on WINDS, and maybe as much as six weeks, and I cannot afford that. With David Benioff, D.B. Weiss, and Bryan Cogman on board, the scriptwriting chores for season six should be well covered. My energies are best devoted to WINDS. "</li>
      <br>  <li> <b>Will George RR Martin ever finish the books?</b> - "Do you think George R.R. Martin will ever finish his books? Nope. Not a chance. He has yet to finish the second to last book, it's taken something like 10 years. "</li>
      <br> <li> <b>How much money did George RR Martin get from Game of Thrones?</b> - "How much did Martin make from the show? We know that Martin was paid about $25 million a year, $15 million of that being a paycheck per season of Game of Thrones. With 7 seasons under his belt, Martin made $150 million from HBO and that is not including the rights to the show. "</li>
      <br> <li> <b>What season did Game of Thrones stop following the books?</b> - "The already formidable number of fans of the series were augmented after HBO's TV adaptation called 'Game of Thrones' premiered. But the series sped past the books in fifth and sixth seasons and ended in ignominy with seventh and eighth seasons that were written without the aid of any source material."</li>
      <br> <li> <b>How far did the Game of Thrones books go?</b> - "Martin. He began writing the first volume, A Game of Thrones in 1991, publishing it in 1996. Martin originally envisioned the series as a trilogy but as of 2023 has released five out of a planned seven volumes. The fifth and most recent entry in the series, A Dance with Dragons, was published in 2011. "</li>
      <br> <li> <b>Who made the most money from Game of Thrones?</b> - "On-screen brothers Peter Dinklage and Nikolaj Coster-Waldau had the joint highest estimated net worth at around 16 million U.S. dollars apiece "</li>
      <br> <li> <b>Who is the most expensive Game of Thrones actor?</b> - "Nikolaj Coster-Waldau (Jaime Lannister) — $720,000 per episode. Jaime Lannister is another key character that fans have loved since season 1. The earnings of Danish actor Nikolaj Coster-Waldau in this role grew several times and by the final season, he was making $1.2 million per episode. "</li>
      <br> <li> <b>How many Game of Thrones books sold?</b> - " As one of the most successful fantasy series of all time, it achieved iconic status when it was turned into the astonishingly successful TV series Game of Thrones. It has sold more than 90 million copies worldwide and has been translated into 47 languages"</li>
      <br> <li> <b>What is the best Game of Thrones book?</b> - " The Game of Thrones Books Ranked
        #5 – A Feast For Crows. Buy the Book. ...
        #4 – A Dance With Dragons. Buy the Book. ...
        #3 – A Storm of Swords. Buy the Book. ...
        #2 – A Game of Thrones. Buy the Book. ...
        #1 – A Clash of Kings. Buy the Book."</li>
      <br> <li> <b>Are the got books better than the show?</b> - "If the show were exactly the same and it was an original property instead, it would probably be even better received by viewers (though probably less viewed overall.) No question, the books are much better. Even when the show was great early on, it still didn't eclipse the books. "</li>
      <br> <li> <b>When did Game of Thrones get popular?    </b> - "By 2012, after the show had been on the air only one year, Game of Thrones' fan base was named the most devoted of all fandoms by New York magazine's Vulture.com, beating out even devotees of Oprah Winfrey, Star Trek, Star Wars and Twilight. "</li>
      <br> <li> <b>Why is Game of Thrones so popular?</b> - "The cinematic quality of the series, along with its epic scale, contributed to its popularity. Shocking Moments: Game of Thrones was known for its shocking and unexpected moments. Major character deaths, betrayals, and surprising plot twists became defining elements of the show. "</li>
      <br> <li> <b>Are the Game of Thrones books hard to read? </b> - "Readability. In terms of readability, A Game of Thrones comes in with a Flesch Reading Ease score of 87. This puts it in the realm of conversational English, so it should be easily understood and enjoyed by most readers. "</li>
      <br> <li> <b>What is the longest book in the Game of Thrones series?</b> - " A Dance with Dragons', the fifth book in George R.R. Martin's 'A Song of Ice and Fire' series, is the lengthiest of the five currently released books, with a word count of almost 415 thousand, spanning over one thousand pages."</li>
      </ul>
     
      <ul>
        <br>
        <h1><i>Early Life And Works:</i></h1><br>
        <p>"George Raymond Martin (he adopted the confirmation name Richard at 13 years old)[2] was born on September 20, 1948,[14] in Bayonne, New Jersey,[15] the son of longshoreman Raymond Collins Martin and Margaret Brady Martin. His mother's family had once been wealthy, owning a successful construction business, but lost it all in the Great Depression, something Martin was reminded about every day when he passed what used to be his family's dock and house.[16] He has two younger sisters, Darleen and Janet. He is predominantly of Irish descent;[17] a DNA test on the series Finding Your Roots showed him to be 53.6% "British and Irish", 22.4% Ashkenazi Jewish, and 15.6% "Broadly Northwestern European".[18][19]

            The family first lived in a house on Broadway belonging to Martin's great-grandmother. In 1953, they moved to a federal housing project near the Bayonne docks.[20] During Martin's childhood, his world consisted predominantly of "First Street to Fifth Street", between his grade school and his home. This limited world made him want to travel and experience other places, but the only way of doing so was through his imagination, and he became a voracious reader.[21]
            
            Martin began writing and selling monster stories for pennies to other neighborhood children, dramatic readings included. He had to stop once a customer's mother complained about her child's nightmares.[22] He also wrote stories about a mythical kingdom populated by his pet turtles — the turtles died frequently in their toy castle, so he decided they were killing each other off in "sinister plots".[23] Martin had a habit of starting "endless stories" that he never completed, as they did not turn out as well on paper as he had imagined them.[24]
            
            Martin attended Mary Jane Donohoe School and later Marist High School. While there, he became an avid comic-book fan, developing a strong interest in the superheroes being published by Marvel Comics,[25] and later credited Stan Lee for being one of his greatest literary influences; "Maybe Stan Lee is the greatest literary influence on me, even more than Shakespeare or Tolkien."[26] A letter Martin wrote to the editor of Fantastic Four was printed in issue #20 (November 1963); it was the first of many sent, e.g., Fantastic Four #32, #34, and others. Fans who read his letters wrote him letters in turn, and through such contacts, Martin joined the fledgling comics fandom of the era, writing fiction for various fanzines;[27] he bought the first ticket to the world's first Comic-Con, held in New York in 1964.[28][29] In 1965, Martin won comic fandom's Alley Award for Best Fan Fiction for his prose superhero story "Powerman vs. The Blue Barrier".[30]
            
            In 1970, Martin earned a B.S. in journalism with a minor in history from Northwestern University's Medill School of Journalism in Evanston, Illinois, graduating summa cum laude; he went on to complete his M.S. in Journalism in 1971, also from Medill.[31] Eligible for the draft during the Vietnam War, to which he objected, Martin applied for and obtained conscientious objector status;[32] he instead did alternative service work for two years (1972–1974) as a VISTA volunteer, attached to the Cook County Legal Assistance Foundation.[31]"</p>
        <br>
        <h1><i> Career:</i></h1><br>
        <p>"Early writing career
            Martin began selling science fiction short stories professionally in 1970, at age 21. His first sale was "The Hero", sold to Galaxy magazine and published in its February 1971 issue; other sales soon followed. His first story to be nominated for the Hugo Award[33] and Nebula Awards was "With Morning Comes Mistfall", published in 1973 in Analog magazine. In 1975 his story "...for a single yesterday" about a post-apocalyptic timetripper was selected for inclusion in Epoch, a science fiction anthology edited by Roger Elwood and Robert Silverberg. His first novel, Dying of the Light, was completed in 1976 right before he moved to Dubuque and published in 1977. That same year the enormous success of Star Wars had a huge impact on the publishing industry and science fiction, and he sold the novel for the same amount he would make in three years of teaching.[34]
            
            The short stories he was able to sell in his early 20s gave him some profit but not enough to pay his bills, which prevented him from becoming the full-time writer he wanted to be. The need for a day job occurred simultaneously with the American chess craze which followed Bobby Fischer's victory in the 1972 world chess championship. Martin's own chess skills and experience allowed him to be hired as a tournament director for the Continental Chess Association, which ran chess tournaments on the weekends. This gave him a sufficient income, and because the tournaments only ran on Saturdays and Sundays, it allowed him to work as a writer five days a week from 1973 to 1976. By the time the chess bubble subsequently burst and no longer provided an income, he had become much better established as a writer.[35][36]
            
            Teaching
            In the mid-1970s, Martin met English professor George Guthridge from Dubuque, Iowa, at a science fiction convention in Milwaukee. Martin persuaded Guthridge (who later said that at that time he despised science fiction and fantasy) not only to give speculative fiction a second look, but also to write in the field himself. Guthridge has since been a finalist for the Hugo Award and twice for the Nebula Award for science fiction and fantasy. In 1998, Guthridge and Janet Berliner won the Bram Stoker Award for Superior Achievement in the Novel for their Children of the Dusk.[37]
            
            In turn, Guthridge helped Martin in finding a job at Clarke University (then Clarke College). Martin "wasn't making enough money to stay alive" from writing and the chess tournaments, says Guthridge.[38] From 1976 to 1978, Martin was an English and journalism instructor at Clarke, and he became Writer In Residence at the college from 1978 to 1979.[39]
            
            Concentration on writing
            While he enjoyed teaching, the sudden death of friend and fellow author Tom Reamy in late 1977 made Martin reevaluate his own life, and he eventually decided to try to become a full-time writer. In 1979 he resigned from his job and moved from Dubuque to Santa Fe, New Mexico at the end of the year.[40][41] There he would live alone for almost three years, a period he described as tremendously productive in regard of writing.[42]
            
            Martin is a member of the Science Fiction and Fantasy Writers of America (SFWA); he served as the organization's Southwest Regional Director from 1977 to 1979, and as its vice-president from 1996 to 1998.[43] In 1976, for Kansas City's MidAmeriCon, the 34th World Science Fiction Convention (Worldcon), Martin and his friend and fellow writer-editor Gardner Dozois conceived of and organized the first Hugo Losers' Party for the benefit of all past and present Hugo-losing writers on the evening following the convention's Hugo Awards ceremony. Martin was nominated for two Hugos that year but lost both awards, for the novelette "...and Seven Times Never Kill Man" and the novella The Storms of Windhaven, co-written with Lisa Tuttle.[44] Although Martin often writes fantasy or horror, a number of his earlier works are science fiction tales occurring in a loosely defined future history, known informally as "The Thousand Worlds" or "The Manrealm".
            
            In 2017, Martin recalled that he had started writing science fiction-horror hybrids in the late 1970s to disprove a statement from a critic claiming that science fiction and horror were opposites and therefore incompatible. Martin considered Sandkings (1979) the best known of these. Another was the novella Nightflyers (1980), whose screen and television rights were purchased by Vista in 1984, which produced a 1987 film adaptation, Nightflyers, with a screenplay co-written by Martin.[45] Martin was unhappy about having to cut plot elements in order to accommodate the film's small budget.[46] While not a hit at theatres, Martin believes that the film saved his career, and that everything he has written since exists in large part because of it.[47] He has also written at least one piece of political-military fiction, "Night of the Vampyres", collected in Harry Turtledove's anthology The Best Military Science Fiction of the 20th Century (2001).[48]
            
            In 1982, Martin published a vampire novel titled Fevre Dream set in the 19th century on the Mississippi River. Unlike traditional vampire novels, in Fevre Dream vampires are not supernatural creatures, but are rather a different species related to humans created by evolution with superhuman powers. Critic Don D'Amassa has praised Fevre Dream for its strong 19th century atmosphere and wrote: "This is without question one of the greatest vampire novels of all time".[49] Martin followed up Fevre Dream with another horror novel, The Armageddon Rag (1983). The unexpected commercial failure of The Armageddon Rag "essentially destroyed my career as a novelist at the time", he recalled, and made him consider going into real estate instead.[50]
            
            In 1984, the new editor of Baen Books, Betsy Mitchell, called Martin to ask him if he had considered doing a collection of Haviland Tuf adventures. Martin, who had several favorite series characters like Solomon Kane, Elric, Nicholas van Rijn and Magnus Ridolph, had made an attempt to create such a character on his own in the 1970s with his Tuf stories. He was interested, but was too occupied with the writing of his next book, the never-completed novel Black and White and Red All Over, which occupied most of his writing time the same year. But after the failure of The Armageddon Rag, all editors rejected his upcoming novel, and desperate for money, he accepted Mitchell's offer and wrote some more Tuf stories which were collected in Tuf Voyaging, which sold well enough for Mitchell to suggest a sequel. Martin was willing and agreed to do it, but before he got started he got an offer from Hollywood, where producer Philip DeGuere Jr. wanted to adapt The Armageddon Rag into a film. The film adaptation did not happen, but they stayed in touch, and when DeGuere became the producer for the revival of The Twilight Zone, Martin was offered a job as a writer. Working for television paid a lot better than writing literature, so he decided to move to Hollywood to seek a new career.[23][51][52] At first he worked as staff writer for the show, and then as an executive story consultant.
            
            After the CBS series was cancelled, Martin migrated over to the already-underway satirical science fiction series Max Headroom. He worked on scripts and created the show's "Ped Xing" character. However, before his scripts could go into production, the ABC show was cancelled in the middle of its second season. Martin was hired as a writer-producer on the new dramatic fantasy series Beauty and the Beast; in 1989, he became the show's co-supervising producer and wrote 14 of its episodes.
            
            In 1987, Martin published a collection of short horror stories in Portraits of His Children. During this same period, Martin continued working in print media as a book-series editor, this time overseeing the development of the multi-author Wild Cards book series, which takes place in a shared universe in which a small slice of post–World War II humanity gains superpowers after the release of an alien-engineered virus; new titles are published in the ongoing series from Tor Books. In Second Person, Martin "gives a personal account of the close-knit role-playing game (RPG) culture that gave rise to his Wild Cards shared-world anthologies".[53] An important element in the creation of the multiple author series was a campaign of Chaosium's role-playing game Superworld (1983) that Martin ran in Albuquerque.[54] Admitting he became completely obsessed with the game, he stopped writing literature for most of 1983, which he refers to as his "lost year", but his shrinking bank accounts made him realize he had to come up with something, and got the idea that perhaps the stories and characters created in Superworld could somehow become profitable.[55] Martin's own contributions to Wild Cards have included Thomas Tudbury, "The Great and Powerful Turtle", a powerful psychokinetic whose flying "shell" consisted of an armored VW Beetle. As of June 2011, 21 Wild Cards volumes had been published in the series; earlier that same year, Martin signed the contract for the 22nd volume, Low Ball (2014), published by Tor Books. In early 2012, Martin signed another Tor contract for the 23rd Wild Cards volume, High Stakes, which was released in August 2016.[56]
            
            In August 2016, Martin announced that Universal Cable Productions had acquired the rights to adapt the Wild Cards novels into a television series.[57] He noted that he himself would not write for the adaptation due to focusing on A Song of Ice and Fire "</p>
        <br>
        <h1><i> A Song Of Ice And Fire:</i></h1><br>
        <p>"In 1991, Martin briefly returned to writing novels. He had grown frustrated that his TV pilots and screenplays were not getting made[58] and that TV-related production limitations like budgets and episode lengths were forcing him to cut characters and trim battle scenes.[59] This pushed Martin back towards writing books, where he did not have to worry about compromising his imagination.[58] Admiring the works of J. R. R. Tolkien in his childhood, he wanted to write an epic fantasy, though he did not have any specific ideas.[60]

            His epic fantasy series, A Song of Ice and Fire, was inspired by the Wars of the Roses, The Accursed Kings[61] and Ivanhoe. Though Martin originally conceptualized it as being three volumes,[62] it is currently slated to comprise seven. The first, A Game of Thrones, was published in 1996, followed by A Clash of Kings in 1998 and A Storm of Swords in 2000. In November 2005, A Feast for Crows, the fourth novel in this series, became The New York Times No. 1 Bestseller.[63] The fifth book, A Dance with Dragons, was published July 12, 2011, and became an international bestseller, including achieving a No. 1 spot on the New York Times Bestseller List[64] and many others; it remained on the New York Times list for 88 weeks.
            
            In 2012, A Dance With Dragons made the final ballot for science fiction and fantasy's Hugo Award,[65] World Fantasy Award,[66] Locus Poll Award, and the British Fantasy Award;[67] the novel went on to win the Locus Poll Award for Best Fantasy Novel.[68] Two more novels are planned in the series: The Winds of Winter and the final volume A Dream of Spring.
            
            On April 25, 2018, Martin announced the release date of his new book, Fire & Blood, dealing with the history of House Targaryen, which was released on November 20, 2018.[69] Should Martin die before finishing the A Song of Ice and Fire series, former collaborators have said that they will not conclude the series for him.[70]
            
            HBO adaptation of A Song of Ice and Fire
            Main article: Game of Thrones
            HBO Productions purchased the television rights for the A Song of Ice and Fire series in 2007. Although busy completing A Dance With Dragons and other projects, George R. R. Martin was heavily involved in the production of the television series adaptation of his books. Martin's involvement included the selection of a production team and participation in scriptwriting; the opening credits list him as a co-executive producer of the series. The original pilot was shot between October 24 and November 19, 2009, on location in Northern Ireland, Scotland and Morocco.[71] It was received poorly by HBO executives that they did not make a decision for four months after the pilot was delivered.[72] In March 2010, HBO's decision to greenlight the series was announced,[73] with the production of the series scheduled to start June 2010.[74] HBO however demanded the first episode be reshot, and wanted all the scenes from Morocco scrapped.[75] The first episode ("Winter Is Coming") premiered on HBO in the United States and Canada on April 17, 2011. It was seen initially by 2.2 million viewers. The first season was nominated for 13 Emmy Awards, ultimately winning two: one for its opening title credits, and one for Peter Dinklage as Best Supporting Actor.[76]
            
            HBO ordered a second season of Game of Thrones on April 19, 2011, two days after the series premiere.[77] The second season obtained a 15% increase in budget in order to be able to stage the war's most important battle,[78] the Battle of the Blackwater, in episode nine which was written by George R. R. Martin. Filming took place during 106 shooting days. During three-quarters of those, two crews ("Dragon" and "Wolf") were working simultaneously in different locations.[79] Alan Taylor was promoted to co-executive producer and directed four episodes, including the season premiere and finale. David Petrarca and David Nutter each directed two episodes, while series cinematographer Alik Sakharov and filmmaker Neil Marshall directed the remaining two. The second season premiered in the United States on HBO on April 1, 2012, and concluded on June 3, 2012. U.S. viewership rose by approximately 8% over the course of the season, from 3.9 million to 4.2 million by the season finale. The second season won six of the twelve Emmy Awards for which it was nominated.[76]
            
            Game of Thrones rapidly became a critical and commercial success after the second season. HBO renewed the series for a third season on April 10, 2012, nine days after the second season's premiere. Production began in July 2012 [80] and concluded with the wrap of the unit filming in Iceland on November 24, 2012. The third season is based on the first half of the novel A Storm of Swords. Benioff had previously said that A Storm of Swords would need to be adapted in two seasons on account of its length. Benioff and Weiss also noted that they thought of Game of Thrones as an adaptation of the series as a whole, rather than of individual novels, which gave them the liberty to move scenes back and forth across novels according to the requirements of the screen adaptation.[81] Season 3 saw the first significant use of the Valyrian languages, spoken in doomed Valyria and its former colonies in Essos. The constructed languages were developed by linguist David J. Peterson based on the few words Martin invented for the novels. Peterson had previously developed the Dothraki language, used principally in season 1.[82] The third season premiered on HBO on March 31, 2013, and concluded on June 9, 2013. The third season was seen by 14.2 million viewers.[83] It won 2 of the 16 Emmy Awards for which it was nominated.[76]
            
            Two days after third season premiere, HBO ordered the fourth season on April 2, 2013, which began filming in July 2013.[84] The season is adapted primarily from the second half of A Storm of Swords, along with elements of A Feast for Crows and A Dance with Dragons. Showrunners David Benioff and D. B. Weiss co-wrote seven out of ten episodes. The remaining three episodes were written by Bryan Cogman (two episodes), and George R. R. Martin (one episode). For this season, the filming lasted 136 days and was completed on November 21, 2013.[85] The fourth season premiered in the United States on HBO on April 6, 2014, and concluded on June 15, 2014. The season was met with largely positive reviews. It won 4 of the 19 Emmy Awards for which it was nominated.[76] With its fourth season, Game of Thrones has become the most-watched HBO series in history (surpassing the fourth season of The Sopranos which had a gross audience of 18.2 million viewers), averaging 18.4 million viewers across multiple platforms, including live viewing, encores, DVR views, HBO GO and On Demand views.[86]
            
            Up until the fourth season, Martin wrote one episode for each season. In 2022, Martin said that he had been estranged from the show during the production process of the last 4 seasons (starting with season 5).[87] In the early seasons, Martin wrote and read scripts, consulted on casting decisions and visited sets. Over time, however, as he stepped back to focus on his long-delayed next “Thrones” novel, "The Winds of Winter".[87] Following the gargantuan success of the fourth season, HBO ordered the fifth season on April 8, 2014, together with the sixth season, which began filming in July 2014. The season primarily adapts the storylines from A Feast for Crows and A Dance with Dragons, also with original content not found in Martin's novels. This season set a Guinness World Record for winning the highest number of Emmy Awards for a series in a single season and year, winning 12 out of 24 nominations, including Outstanding Drama Series.[88]
            
            With a budget over $100 million for the whole season, filming for the sixth season began in July 2015 and ended on December. The season filmed in five different countries: Northern Ireland, Spain, Croatia, Iceland, and Canada. This season saw the overall plot of the show diverging from the source material. Some of the season's storyline is derived from content not yet published in Martin's A Song of Ice and Fire series, although a significant amount of material from A Feast for Crows, A Dance with Dragons and the upcoming sixth novel The Winds of Winter, which Martin previously outlined to showrunners David Benioff and D.B. Weiss, was used.[89] The season was largely met with positive reviews.[90] The "Battle of the Bastards" episode received immense critical acclaim, with many calling it one of the best television episodes of all time.[91] U.S. viewership rose compared to the previous season, and by approximately 13 percent over its course, from 7.9 million to 8.9 million by the finale. The season won 12 of the 23 Emmy Awards for which it was nominated.[76]
            
            Three days before the premiere of the episode "The Red Woman", HBO ordered the seventh season. Due to necessary weather conditions required for filming, the production of the penultimate season of the show was delayed that year.[92] Filming began only on August 31, 2016, at Titanic Studios in Belfast,[93] and ended in February 2017.[94] Unlike previous seasons, the seventh and eighth seasons largely consisted of original content not found in the source material. This season comprised only seven episodes. The showrunners stated that they were unable to produce 10 episodes in the show's usual 12 to 14 month time frame, as Weiss said "It's crossing out of a television schedule into more of a mid-range movie schedule".[95] The average runtime of an episode in this season was approximately 63 minutes. The series received 22 nominations for the 70th Primetime Emmy Awards and won 9 of them, including "Outstanding Drama Series".[96]
            
            Unlike its prior seasons, the final one took a year gap for its production and filming. The eighth season consisted of only six episodes, though the average runtime of an episode was 68 minutes, the longest of all seasons, with "The Long Night" consisting of 81 minutes. The season was met with mixed reviews from critics, with the performances, production values and music score were praised, criticism was mainly directed at the shorter runtime of the season as well as numerous creative decisions made by the showrunners. Many commentators deemed it to be a disappointing conclusion to the series. The season received 32 nominations at the 71st Primetime Emmy Awards, the most for a single season of television in history. It won twelve, including Outstanding Drama Series and Outstanding Supporting Actor in a Drama Series for Peter Dinklage.[97]
            
            Three years after the show ended, a prequel series, House of the Dragon, premiered on HBO in August 21, 2022. Based on parts of the novel Fire & Blood, the series is set about 200 years before the events of Game of Thrones. Ryan Condal and Miguel Sapochnik served as the showrunners for the first season. Five days after its premiere, the series was renewed for a second season by HBO. On September 1, Sapochnik departed as showrunner,[98] with another veteran Game of Thrones director Alan Taylor replacing him as the co-showrunner for the upcoming second season.[99]
            
            In June 2022, it was reported that a Jon Snow sequel series with Kit Harington to reprise his role was in early development at HBO.[100] The working title is Snow and Martin confirmed his involvement with the project and that Harington initiated the idea.[101] Also in June, Martin said there were still three other live-action series in development: 10,000 Ships (written by Amanda Segal), 9 Voyages aka Sea Snake (written by Bruno Heller), and the Dunk & Egg prequel series (written by Steven Conrad), tentatively titled either The Hedge Knight or Knight of the Seven Kingdoms.[101]
            
            In January 2021, an animated drama series was announced as in development at HBO Max.[102] In July 2021, two more animated series were in development at HBO Max, with one being set in Yi Ti, a nation in Essos loosely based on Imperial China "</p>

    
      <br>
      </ul>
      <br>
      <p class="link"><b>If you have time, you should read more about this incredible human being on his 
        <a href="https://en.wikipedia.org/wiki/George_R._R._Martin">Wikipedia</a>
        .</b></p>
    </div>
    
    </div>
    
    
    <!-- Footer Code Start -->
<?php include 'footer.php'; ?> 
    
</body>
</html>