<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Henry James</title>
    <!-- Font Awesome CDN Link -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- CSS File Link -->
  <link rel="stylesheet" href="css/style3.css">
  <link rel="stylesheet" href="css/style.css">

</head>
<body>
<div class="henry-heading">
   <h3>Author Henry</h3>
   <p> <a href="about.php">About Us</a> / Author Henry</p>
</div>

<div class="division0">
    <h1 class="walker-heading"> HENRY JAMES </h1>
    <i class="walker-sub-heading"> U.S. British novelist </i>
    
    <div class="division1">
      <img src= "images/au1.jpg"><br><br>
      <p class="main">Henry James, (born April 15, 1843, New York, N.Y., U.S.—died Feb. 28, 1916, London, Eng.)</p>
    </div>
    
    <div class="division2">
      <b>
    <i class="alice-life">Here's a time line of HENRY's life:</i>
    </b><br><br>
      <ul>
        <li> <b>Born</b> - April 15, 1843, New York, New York, U.S.</li>
      <br>  <li> <b>Who was Henry James?</b> - "Henry James was an American novelist and critic. During his lifetime he wrote 20 novels, 112 tales, and 12 plays in addition to several volumes of travel writing and criticism. Today he is best remembered as the author of the novel The Portrait of a Lady (1881) and the novella The Turn of the Screw (1898)."</li>
      <br>  <li> <b>Where did Henry James grow up?</b> - "Henry James was born on April 15, 1843, in New York City. James was a well-traveled youth. As a teenager, he visited Geneva, Paris, and London. Just before the American Civil War, the James family moved to New England. Before pursuing a career as a writer, James briefly attended Harvard Law School."</li>
      <br> <li> <b>When did Henry James become a writer?</b> - "Henry James’s first short story, “A Tragedy of Error,” was published anonymously in The Continental Monthly in 1864. Shortly thereafter James befriended William Dean Howells, editor of The Atlantic Monthly. Howells published him regularly, and by his mid-20s James was widely considered one of the most skillful writers of short stories in America."</li>
      <br> <li> <b>How did Henry James influence the development of the novel?</b> - "Henry James was a key transitional figure between literary realism and Modernism. James was interested in human behaviour and the inner workings of the mind. In his novels, he employed Modernist techniques such as stream-of-consciousness narration to explore the psychology of his characters, focusing in particular on the effect of external events on individual consciousness."</li>
      <br> <li> <b>What are some of Henry James’s most famous works?</b> -  "Henry James was one of the most prolific writers of the 19th century. His most famous works included The Portrait of a Lady (1881), The Bostonians (1886), and The Ambassadors (1903). Many of his tales, including “The Figure in the Carpet” (1896) and The Turn of the Screw (1898), are still widely read."</li>
      <br> <li> <b>How did Henry James die?</b> - "Henry James spent the last several years of his life in Great Britain. In protest of U.S. neutrality in World War I, James resigned his U.S. citizenship and became a British subject in 1915. He died of pneumonia on February 28, 1916, a year before the United States entered the war."</li>
      <br> <li> <b>What is Henry James most famous for?</b> - "Henry James was an American novelist and critic. During his lifetime he wrote 20 novels, 112 tales, and 12 plays in addition to several volumes of travel writing and criticism. Today he is best remembered as the author of the novel The Portrait of a Lady (1881) and the novella The Turn of the Screw (1898)."</li>
      <br> <li> <b>What are the characteristics of Henry James?</b> - "Social Realism Henry James (1843-1916) Henry James (1843-1916) Known for his sophisticated style, precise language, extraordinary productivity, and innovative attention to the novel form, Henry James ranks among the greatest American writers."</li>
      <br> <li> <b>Why is Henry James a good writer?</b> - "Henry James's career was one of the longest and most productive—and most influential—in American letters. A master of prose fiction from the first, he practiced it as a fertile innovator, enlarged the form, and placed upon it the stamp of a highly individual method and style."</li>
      <br> <li> <b>Did Henry James win Nobel Prize?</b> - "Neither Henry James nor his friend Edith Wharton (right) won a Nobel Prize, like many other great American writers. And yet, despite the obvious cluelessness of these judges, many of those passed over have nevertheless been exceedingly uncool about being rejected."</li>
      <br> <li> <b>What is Henry James greatest novel?</b> - "The Portrait of a Lady. Having spent the last few years rereading most of James in preparation for writing my book, I consider The Portrait of a Lady his most perfect novel."</li>
      <br> <li> <b>What is the theme of the Henry James books?</b> - "His fundamental theme was the innocence and exuberance of the New World in clash with the corruption and wisdom of the Old, as illustrated in such works as Daisy Miller (1879), The Portrait of a Lady (1881), The Bostonians (1886), and The Ambassadors (1903)."</li>
      <br> <li> <b>What is the title of Henry's first published story?</b> - "he first story published as O. Henry was “Whistling Dick's Christmas Stocking.” Appearing in McClure's magazine in December 1899, it tells the tale of a “professional tramp,” a fateful gift from a passing surry, and a good night's sleep on Christmas Eve. Released after three years for good behavior, O."</li>
      <br> <li> <b>What is the realism of Henry James?</b> - "More consistently and more explicitly than any of his contemporaries, American or European, Henry James recognized literary realism as the attempt not to reproduce the real directly, but rather to create an impression of it – to evoke for readers the 'sense', the 'air', 'the odour', the 'strange, irregular rhythm' "</li>
      <br> <li> <b>What were the theories of Henry James?</b> - "James' central claim is that the novelist and the novel must be free. Finally, James is highly conscious of a puritanical environment which views art as having an injurious effect, and as opposed to morality, amusement, or instruction."</li>
    <br> <li> <b>Died</b> - February 28, 1916, London, England (aged 72)</li><br><br>
      </ul>
     
      <ul>
        
        <h1><i>Early Life And Works:</i></h1><br>
        <p>"Henry James was named for his father, a prominent social theorist and lecturer, and was the younger brother of the pragmatist philosopher William James. The young Henry was a shy, book-addicted boy who assumed the role of quiet observer beside his active elder brother. They were taken abroad as infants, were schooled by tutors and governesses, and spent their preadolescent years in Manhattan. Returned to Geneva, Paris, and London during their teens, the James children acquired languages and an awareness of Europe vouchsafed to few Americans in their times. On the eve of the American Civil War, the James family settled at Newport, Rhode Island, and there, and later in Boston, Henry came to know New England intimately. When he was 19 years of age, he enrolled at the Harvard Law School, but he devoted his study time to reading Charles Augustin Sainte-Beuve, Honoré de Balzac, and Nathaniel Hawthorne. His first story appeared anonymously two years later in the New York Continental Monthly and his first book reviews in the North American Review. When William Dean Howells became editor of The Atlantic Monthly, James found in him a friend and mentor who published him regularly. Between them, James and Howells inaugurated the era of American “realism.”

            By his mid-20s James was regarded as one of the most skillful writers of short stories in America. Critics, however, deplored his tendency to write of the life of the mind, rather than of action. The stories of these early years show the leisurely existence of the well-to-do at Newport and Saratoga. James’s apprenticeship was thorough. He wrote stories, reviews, and articles for almost a decade before he attempted a full-length novel. There had to be also the traditional “grand tour,” and James went abroad for his first adult encounter with Europe in 1869. His year’s wandering in England, France, and Italy set the stage for a lifetime of travel in those countries. James never married. By nature he was friendly and even gregarious, but, while he was an active observer and participant in society, he tended, until late middle age, to be “distant” in his relations with people and was careful to avoid “involvement.”"</p>
        <br>
        <h1><i>Career First Phase:</i></h1><br>
        <p>"Recognizing the appeal of Europe, given his cosmopolitan upbringing, James made a deliberate effort to discover whether he could live and work in the United States. Two years in Boston, two years in Europe, mainly in Rome, and a winter of unremitting hackwork in New York City convinced him that he could write better and live more cheaply abroad. Thus began his long expatriation—heralded by publication in 1875 of the novel Roderick Hudson, the story of an American sculptor’s struggle by the banks of the Tiber between his art and his passions; Transatlantic Sketches, his first collection of travel writings; and a collection of tales. With these three substantial books, he inaugurated a career that saw about 100 volumes through the press during the next 40 years. During 1875–76 James lived in Paris, writing literary and topical letters for the New York Tribune and working on his novel The American (1877), the story of a self-made American millionaire whose guileless and forthright character contrasts with that of the arrogant and cunning family of French aristocrats whose daughter he unsuccessfully attempts to marry. In Paris James sought out the Russian novelist Ivan Turgenev, whose work appealed to him, and through Turgenev was brought into Gustave Flaubert’s coterie, where he got to know Edmond de Goncourt, Émile Zola, Alphonse Daudet, and Guy de Maupassant. From Turgenev he received confirmation of his own view that a novelist need not worry about “story” and that, in focusing on character, he would arrive at the life experience of his protagonist.

            Much as he liked France, James felt that he would be an eternal outsider there, and late in 1876 he crossed to London. There, in small rooms in Bolton Street off Piccadilly, he wrote the major fiction of his middle years. In 1878 he achieved international renown with his story of an American flirt in Rome, Daisy Miller, and further advanced his reputation with The Europeans that same year. In England he was promptly taken up by the leading Victorians and became a regular at Lord Houghton’s breakfasts, where he consorted with Alfred Tennyson, William Gladstone, Robert Browning, and others. A great social lion, James dined out 140 times during 1878 and 1879 and visited in many of the great Victorian houses and country seats. He was elected to London clubs, published his stories simultaneously in English and American periodicals, and mingled with George Meredith, Robert Louis Stevenson, Edmund Gosse, and other writers, thus establishing himself as a significant figure in Anglo-American literary and artistic relations.  James’s reputation was founded on his versatile studies of “the American girl.” In a series of witty tales, he pictured the “self-made” young woman, the bold and brash American innocent who insists upon American standards in European society. James ended this first phase of his career by producing his masterpiece, The Portrait of a Lady (1881), a study of a young woman from Albany who brings to Europe her narrow provincialism and pretensions but also her sense of her own sovereignty, her “free spirit,” her refusal to be treated, in the Victorian world, merely as a marriageable object. As a picture of Americans moving in the expatriate society of England and of Italy, this novel has no equal in the history of modern fiction. It is a remarkable study of a band of egotists while at the same time offering a shrewd appraisal of the American character. James’s understanding of power in personal relations was profound, as evinced in Washington Square (1881), the story of a young American heroine whose hopes for love and marriage are thwarted by her father’s callous rejection of a somewhat opportunistic suitor."</p>
        <br>
        <h1><i>Career Middle Phase:</i></h1><br>
        <p>"In the 1880s James wrote two novels dealing with social reformers and revolutionaries, The Bostonians (1886) and The Princess Casamassima (1886). In the novel of Boston life, James analyzed the struggle between conservative masculinity embodied in a Southerner living in the North and an embittered man-hating suffragist. The Bostonians remains the fullest and most-rounded American social novel of its time in its study of cranks, faddists, and “do-gooders.” In The Princess Casamassima James exploited the anarchist violence of the decade and depicted the struggle of a man who toys with revolution and is destroyed by it. These novels were followed by The Tragic Muse (1890), in which James projected a study of the London and Paris art studios and the stage, the conflict between art and “the world.”

            The latter novel raised the curtain on his own “dramatic years,” 1890–95, during which he tried to win success writing for the stage. His dramatization of The American in 1891 was a modest success, but an original play, Guy Domville, produced in 1895, was a failure, and James was booed at the end of the first performance. Crushed and feeling that he had lost his public, he spent several years seeking to adapt his dramatic experience to his fiction. The result was a complete change in his storytelling methods. In The Spoils of Poynton (1897), What Maisie Knew (1897), The Turn of the Screw and In the Cage (1898), and The Awkward Age (1899), James began to use the methods of alternating “picture” and dramatic scene, close adherence to a given angle of vision, a withholding of information from the reader, making available to him only that which the characters see. The subjects of this period are the developing consciousness and moral education of children—in reality James’s old international theme of innocence in a corrupting world, transferred to the English setting."</p>
        <br>
        <h1><i>Career Final Phase:</i></h1><br>
        <p>"The experiments of this “transition” phase led James to the writing of three grandiose novels at the beginning of the new century, which represent his final—his “major”—phase, as it has been called. In these novels James pointed the way for the 20th-century novel. He had begun as a realist who describes minutely his crowded stage. He ended by leaving his stage comparatively bare, and showing a small group of characters in a tense situation, with a retrospective working out, through multiple angles of vision, of their drama. In addition to these technical devices he resorted to an increasingly allusive prose style, which became dense and charged with symbolic imagery. His late “manner” derived in part from his dictating directly to a typist and in part from his unremitting search for ways of projecting subjective experience in a flexible prose.

            The first of the three novels was The Ambassadors (1903). This is a high comedy of manners, of a middle-aged American who goes to Paris to bring back to a Massachusetts industrial town a wealthy young man who, in the view of his affluent family, has lingered too long abroad. The “ambassador” in the end is captivated by civilized Parisian life. The novel is a study in the growth of perception and awareness in the elderly hero, and it balances the relaxed moral standards of the European continent against the parochial rigidities of New England. The second of this series of novels was The Wings of the Dove, published in 1902, before The Ambassadors, although written after it. This novel, dealing with a melodramatic subject of great pathos, that of an heiress doomed by illness to die, avoids its cliche subject by focusing upon the characters surrounding the unfortunate young woman. They intrigue to inherit her millions. Told in this way, and set in London and Venice, it becomes a powerful study of well-intentioned humans who, with dignity and reason, are at the same time also birds of prey. In its shifting points of view and avoidance of scenes that would end in melodrama, The Wings of the Dove demonstrated the mastery with which James could take a tawdry subject and invest it with grandeur. His final novel was The Golden Bowl (1904), a study of adultery, with four principal characters. The first part of the story is seen through the eyes of the aristocratic husband and the second through the developing awareness of the wife.
            
            While many of James’s short stories were potboilers written for the current magazines, he achieved high mastery in the ghostly form, notably in The Turn of the Screw (1898), and in such remarkable narratives as “The Aspern Papers” (1888) and “The Beast in the Jungle” (1903)—his prophetic picture of dissociated 20th-century man lost in an urban agglomeration. As a critic, James tended to explore the character and personality of writers as revealed in their creations; his essays are a brilliant series of studies, moral portraits, of the most famous novelists of his century, from Balzac to the Edwardian realists. His travel writings, English Hours (1905), Italian Hours (1909), and A Little Tour in France (1884), portray the backgrounds James used for his fictions.
            
            In his later years, James lived in retirement in an 18th-century house at Rye in Sussex, though on completion of The Golden Bowl he revisited the United States in 1904–05. James had lived abroad for 20 years, and in the interval America had become a great industrial and political power. His observation of the land and its people led him to write, on his return to England, a poetic volume of rediscovery and discovery, The American Scene (1907), prophetic in its vision of urban doom, spoliation, and pollution of resources and filled with misgivings over the anomalies of a “melting pot” civilization. The materialism of American life deeply troubled James, and on his return to England he set to work to shore up his own writings, and his own career, against this ephemeral world. He devoted three years to rewriting and revising his principal novels and tales for the highly selective “New York Edition,” published in 24 volumes. For this edition James wrote 18 significant prefaces, which contain both reminiscence and exposition of his theories of fiction.
            
            Throwing his moral weight into Britain’s struggle in World War I, James became a British subject in 1915 and received the Order of Merit (O.M.) from King George V."</p>

      <br>
      </ul>
      <br><br>
      <p class="link"><b>If you have time, you should read more about this incredible human being on his 
        <a href="https://en.wikipedia.org/wiki/Henry_James">Wikipedia</a>
        .</b></p>
    </div>
    
    </div>
    
   
    <!-- Footer Code Start -->
<?php include 'footer.php'; ?> 
</body>
</html>